<%@ Page Title="Medical History" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="Medical_History.aspx.cs" Inherits="masterr.Pages.Medical_History" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    
     <style>

        body
        
  {

              background-image:url("../Images/white1.jpg");
            background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;

    /*background:linear-gradient(rgb(153,217,220), rgb(83,203,255));
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

        <div class="container">
        <div class="jumbotron">
            <h3 class="h1 texy-center" style="text-align:center;">Medical History</h3>

            <div id="Admin">
                <asp:GridView CssClass="table table-striped table-bordered table-condensed"  ID="Admin" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="user_id" DataSourceID="Admin_V">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                        <asp:BoundField DataField="Weight" HeaderText="Weight" SortExpression="Weight" />
                        <asp:BoundField DataField="Height" HeaderText="Height" SortExpression="Height" />
                        <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                        <asp:BoundField DataField="condition" HeaderText="condition" SortExpression="condition" />
                        <asp:BoundField DataField="user_id" HeaderText="user_id" InsertVisible="False" ReadOnly="True" SortExpression="user_id" />
                    </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Users] WHERE [user_id] = @user_id" InsertCommand="INSERT INTO [Users] ([Name], [DOB], [Weight], [Height], [age], [condition]) VALUES (@Name, @DOB, @Weight, @Height, @age, @condition)" SelectCommand="SELECT [Name], [DOB], [Weight], [Height], [age], [condition], [user_id] FROM [Users] where role_id='3'" UpdateCommand="UPDATE [Users] SET [Name] = @Name, [DOB] = @DOB, [Weight] = @Weight, [Height] = @Height, [age] = @age, [condition] = @condition WHERE [user_id] = @user_id">
                    <DeleteParameters>
                        <asp:Parameter Name="user_id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Name" Type="String" />
                        <asp:Parameter DbType="Date" Name="DOB" />
                        <asp:Parameter Name="Weight" Type="Int32" />
                        <asp:Parameter Name="Height" Type="Int32" />
                        <asp:Parameter Name="age" Type="Int32" />
                        <asp:Parameter Name="condition" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Name" Type="String" />
                        <asp:Parameter DbType="Date" Name="DOB" />
                        <asp:Parameter Name="Weight" Type="Int32" />
                        <asp:Parameter Name="Height" Type="Int32" />
                        <asp:Parameter Name="age" Type="Int32" />
                        <asp:Parameter Name="condition" Type="String" />
                        <asp:Parameter Name="user_id" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>

            </div>

            <div id="Instructor">
                <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="User" runat="server" AutoGenerateColumns="False" DataSourceID="User_V">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                        <asp:BoundField DataField="Weight" HeaderText="Weight" SortExpression="Weight" />
                        <asp:BoundField DataField="Height" HeaderText="Height" SortExpression="Height" />
                        <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                        <asp:BoundField DataField="condition" HeaderText="condition" SortExpression="condition" />
                    </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="User_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Name], [DOB], [Weight], [Height], [age], [condition] FROM [Users] where role_id='3'"></asp:SqlDataSource>

            </div>



            </div>
            </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
