<%@ Page Title="View Notification" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Notification.aspx.cs" Inherits="masterr.Pages.View_Notification" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">


     <style>

        body
        
  {
        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;

    /*background:linear-gradient(rgb(153,217,220), rgb(83,203,255));
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }
    </style>


</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="container">
        <div class="jumbotron">
            <h3 class="h1 texy-center" style="text-align:center;">Notifications</h3>
            <div>
                <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Admin" runat="server" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="Admin_V" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                    <Columns>
                        <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                        <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                        <asp:BoundField DataField="Notification" HeaderText="Notification" SortExpression="Notification" />
                        <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Notification] WHERE [id] = @id" InsertCommand="INSERT INTO [Notification] ([Title], [Notification], [Date]) VALUES (@Title, @Notification, @Date)" SelectCommand="SELECT * FROM [Notification]" UpdateCommand="UPDATE [Notification] SET [Title] = @Title, [Notification] = @Notification, [Date] = @Date WHERE [id] = @id">
                    <DeleteParameters>
                        <asp:Parameter Name="id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Title" Type="String" />
                        <asp:Parameter Name="Notification" Type="String" />
                        <asp:Parameter Name="Date" Type="DateTime" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Title" Type="String" />
                        <asp:Parameter Name="Notification" Type="String" />
                        <asp:Parameter Name="Date" Type="DateTime" />
                        <asp:Parameter Name="id" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div>

            <div>

                <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="User" runat="server" AutoGenerateColumns="False" DataSourceID="User_V">
                    <Columns>
                        <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                        <asp:BoundField DataField="Notification" HeaderText="Notification" SortExpression="Notification" />
                        <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="User_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Title], [Notification], [Date] FROM [Notification]"></asp:SqlDataSource>
            </div>



        </div>
    </div>



</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
