<%@ Page Title="View Diet" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Diet.aspx.cs" Inherits="masterr.Pages.View_Diet" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

 <style>

        body
        
  {


        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;

        /*background:linear-gradient(rgb(153,217,220), rgb(83,203,255));
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }
    </style>


</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <div class="jumbotron">
                            <h3 class="h1 texy-center" style="text-align:center;"> Diet</h3>
            <asp:gridview CssClass="table table-striped table-bordered table-condensed" runat="server" ID="Admin" AutoGenerateColumns="False" DataKeyNames="Diet_id" DataSourceID="Admin_V" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="Diet_id" HeaderText="Diet_id" InsertVisible="False" ReadOnly="True" SortExpression="Diet_id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                </Columns>
            </asp:gridview>
            <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Diet] WHERE [Diet_id] = @Diet_id" InsertCommand="INSERT INTO [Diet] ([Name], [Description]) VALUES (@Name, @Description)" SelectCommand="SELECT * FROM [Diet]" UpdateCommand="UPDATE [Diet] SET [Name] = @Name, [Description] = @Description WHERE [Diet_id] = @Diet_id">
                <DeleteParameters>
                    <asp:Parameter Name="Diet_id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                    <asp:Parameter Name="Diet_id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>


            <asp:gridview CssClass="table table-striped table-bordered table-condensed" runat="server" ID="User" AutoGenerateColumns="False" DataSourceID="User_V">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                </Columns>
            </asp:gridview>


            <asp:SqlDataSource ID="User_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Name], [Description] FROM [Diet]"></asp:SqlDataSource>


        </div>
    </div>

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
