<%@ Page Title="View Class" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Class.aspx.cs" Inherits="masterr.Pages.View_Class" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">


     <style>

        body
        
  {


        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;
    
    /*background:linear-gradient(rgb(153,217,220), rgb(83,203,255));
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }

    </style>


</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<div class="container">
<div class="jumbotron">
<h3 class="h1 texy-center" style="text-align:center;"> Class Details</h3>
<div>
    <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Admin" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Class_id" DataSourceID="Admin_V">
        <Columns>
            <asp:BoundField DataField="Class_id" HeaderText="Class_id" InsertVisible="False" ReadOnly="True" SortExpression="Class_id" />
            <asp:BoundField DataField="Class_Title" HeaderText="Class_Title" SortExpression="Class_Title" />
            <asp:BoundField DataField="Class_Date" HeaderText="Class_Date" SortExpression="Class_Date" />
            <asp:BoundField DataField="Class_Time" HeaderText="Class_Time" SortExpression="Class_Time" />
            <asp:BoundField DataField="Class_Day" HeaderText="Class_Day" SortExpression="Class_Day" />
            <asp:BoundField DataField="Class_Instructor" HeaderText="Class_Instructor" SortExpression="Class_Instructor" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Class] WHERE [Class_id] = @Class_id" InsertCommand="INSERT INTO [Class] ([Class_Title], [Class_Date], [Class_Time], [Class_Day], [Class_Instructor]) VALUES (@Class_Title, @Class_Date, @Class_Time, @Class_Day, @Class_Instructor)" SelectCommand="SELECT * FROM [Class]" UpdateCommand="UPDATE [Class] SET [Class_Title] = @Class_Title, [Class_Date] = @Class_Date, [Class_Time] = @Class_Time, [Class_Day] = @Class_Day, [Class_Instructor] = @Class_Instructor WHERE [Class_id] = @Class_id">
        <DeleteParameters>
            <asp:Parameter Name="Class_id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Class_Title" Type="String" />
            <asp:Parameter DbType="Date" Name="Class_Date" />
            <asp:Parameter Name="Class_Time" Type="String" />
            <asp:Parameter Name="Class_Day" Type="String" />
            <asp:Parameter Name="Class_Instructor" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Class_Title" Type="String" />
            <asp:Parameter DbType="Date" Name="Class_Date" />
            <asp:Parameter Name="Class_Time" Type="String" />
            <asp:Parameter Name="Class_Day" Type="String" />
            <asp:Parameter Name="Class_Instructor" Type="String" />
            <asp:Parameter Name="Class_id" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
</div>


<div>

    <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="User" runat="server" AutoGenerateColumns="False" DataSourceID="User_V">
        <Columns>
            <asp:BoundField DataField="Class_Title" HeaderText="Class_Title" SortExpression="Class_Title" />
            <asp:BoundField DataField="Class_Date" HeaderText="Class_Date" SortExpression="Class_Date" />
            <asp:BoundField DataField="Class_Time" HeaderText="Class_Time" SortExpression="Class_Time" />
            <asp:BoundField DataField="Class_Day" HeaderText="Class_Day" SortExpression="Class_Day" />
            <asp:BoundField DataField="Class_Instructor" HeaderText="Class_Instructor" SortExpression="Class_Instructor" />
        </Columns>
    </asp:GridView>

    <asp:SqlDataSource ID="User_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Class_Title], [Class_Date], [Class_Time], [Class_Day], [Class_Instructor] FROM [Class]"></asp:SqlDataSource>

</div>

    <div>

        <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Instructor" runat="server"></asp:GridView>
    </div>

</div>
</div>


</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
