<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Target.aspx.cs" Inherits="masterr.Pages.View_Target" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

      <style>

        body
        
  {

        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;
    
        /*background:radial-gradient(rgb(153,217,220) , rgb(83,203,255) );
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }
    </style>


</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<div class="container">
<div class="jumbotron">
<h3 class="h1 texy-center" style="text-align:center;"> View Target</h3>

<div id="Admins">
    <asp:gridview CssClass="table table-striped table-bordered table-condensed" runat="server" ID="Admin" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="Admin_V" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
            <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
            <asp:BoundField DataField="C_date" HeaderText="C_date" SortExpression="C_date" />
            <asp:BoundField DataField="end_date" HeaderText="end_date" SortExpression="end_date" />
            <asp:BoundField DataField="C_weight" HeaderText="C_weight" SortExpression="C_weight" />
            <asp:BoundField DataField="E_weight" HeaderText="E_weight" SortExpression="E_weight" />
            <asp:BoundField DataField="member" HeaderText="member" SortExpression="member" />
        </Columns>
    </asp:gridview>
    <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Target] WHERE [id] = @id" InsertCommand="INSERT INTO [Target] ([title], [description], [C_date], [end_date], [C_weight], [E_weight], [member]) VALUES (@title, @description, @C_date, @end_date, @C_weight, @E_weight, @member)" SelectCommand="SELECT * FROM [Target]" UpdateCommand="UPDATE [Target] SET [title] = @title, [description] = @description, [C_date] = @C_date, [end_date] = @end_date, [C_weight] = @C_weight, [E_weight] = @E_weight, [member] = @member WHERE [id] = @id">
        <DeleteParameters>
            <asp:Parameter Name="id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="title" Type="String" />
            <asp:Parameter Name="description" Type="String" />
            <asp:Parameter DbType="Date" Name="C_date" />
            <asp:Parameter DbType="Date" Name="end_date" />
            <asp:Parameter Name="C_weight" Type="String" />
            <asp:Parameter Name="E_weight" Type="String" />
            <asp:Parameter Name="member" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="title" Type="String" />
            <asp:Parameter Name="description" Type="String" />
            <asp:Parameter DbType="Date" Name="C_date" />
            <asp:Parameter DbType="Date" Name="end_date" />
            <asp:Parameter Name="C_weight" Type="String" />
            <asp:Parameter Name="E_weight" Type="String" />
            <asp:Parameter Name="member" Type="String" />
            <asp:Parameter Name="id" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
</div>

<div id="Member">
    <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="User" runat="server"></asp:GridView>
</div>


</div>
</div>




</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
