<%@ Page Title="View Exercise Plan" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Exercise_Plan.aspx.cs" Inherits="masterr.Pages.View_Exercise_Plan" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

     <style>

        body
        
  {

        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;

        /*background:radial-gradient(rgb(153,217,220) , rgb(83,203,255) );
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }
    </style>


</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<div class="container">
<div class="jumbotron">
<h3 class="h1 texy-center" style="text-align:center;"> View Exercise Plan</h3>
<div style="margin:auto;margin-left:380px;">
<table class="table-hover">
<tr><td><asp:Button CssClass=" btn btn-default"  ID="General" runat="server" Text="General" OnClick="General_Click" /></td><td><asp:Button CssClass="btn btn-default" ID="Specific" runat="server" Text="Specific" OnClick="Specific_Click" /></td></tr>
</table>
</div>
<div id="Admin/Instructor Gridview">
    <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Admin" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="Admin_V">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:BoundField DataField="Member" HeaderText="Member" SortExpression="Member" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Exercise_Plan] WHERE [id] = @id" InsertCommand="INSERT INTO [Exercise_Plan] ([Title], [Description], [Member]) VALUES (@Title, @Description, @Member)" SelectCommand="SELECT * FROM [Exercise_Plan]" UpdateCommand="UPDATE [Exercise_Plan] SET [Title] = @Title, [Description] = @Description, [Member] = @Member WHERE [id] = @id">
        <DeleteParameters>
            <asp:Parameter Name="id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Title" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
            <asp:Parameter Name="Member" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Title" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
            <asp:Parameter Name="Member" Type="String" />
            <asp:Parameter Name="id" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
</div>

<div id="Member GridView">
    <div id="general view">
        <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="General_GV" runat="server" AutoGenerateColumns="False" DataSourceID="User_V" AllowPaging="True">
            <Columns>
                <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="User_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Title] , [Description] FROM [Exercise_Plan] where [Member]='General'"></asp:SqlDataSource>
    </div>


</div>
    <div id="Specific view">
        <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Specific_V" runat="server"></asp:GridView>
    </div>
</div>
</div>

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
