<%@ Page Title="View Exercise" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Exercise.aspx.cs" Inherits="masterr.Pages.View_Exercise" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">



    <style>

        body
        
  {

        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;

    
    /*background:linear-gradient(rgb(153,217,220), rgb(83,203,255));
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }

    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <div class="jumbotron">
         <h3 class="h1 texy-center" style="text-align:center;"> Exercise</h3>


            <asp:gridview CssClass="table table-striped table-bordered table-condensed" runat="server" ID="Admin" AutoGenerateColumns="False" DataKeyNames="Exercise_id" DataSourceID="Admin_V" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="Exercise_id" HeaderText="Exercise_id" InsertVisible="False" ReadOnly="True" SortExpression="Exercise_id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                </Columns>
            </asp:gridview>


            <asp:SqlDataSource ID="Admin_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Exercise] WHERE [Exercise_id] = @Exercise_id" InsertCommand="INSERT INTO [Exercise] ([Name], [Description]) VALUES (@Name, @Description)" SelectCommand="SELECT * FROM [Exercise]" UpdateCommand="UPDATE [Exercise] SET [Name] = @Name, [Description] = @Description WHERE [Exercise_id] = @Exercise_id">
                <DeleteParameters>
                    <asp:Parameter Name="Exercise_id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                    <asp:Parameter Name="Exercise_id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>


            <asp:gridview CssClass="table table-striped table-bordered table-condensed"  runat="server" ID="Users" AutoGenerateColumns="False" DataSourceID="User_V">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                </Columns>
            </asp:gridview>


            <asp:SqlDataSource ID="User_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Name], [Description] FROM [Exercise]"></asp:SqlDataSource>


        </div>

    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
