<%@ Page Title="View Instructor" Language="C#" MasterPageFile="~/Pages/Main.Master" AutoEventWireup="true" CodeBehind="View_Instructor.aspx.cs" Inherits="masterr.Pages.View_Instructor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>

        body
        
  {

        background-image:url("../Images/white7.png");
        background-size:cover;
        display: block;
        max-width: 100%;
        height: auto;
    
        /*background:linear-gradient(rgb(153,217,220), rgb(83,203,255));
        display: block;
        max-width: 100%;
        height: auto;
        padding-bottom:150px;*/

    }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="container">
        <div class="jumbotron">
                <h3 class="h1 texy-center" style="text-align:center;"> Instructors</h3>

            <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Admin" runat="server" AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="user_id" DataSourceID="Instructor_V" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="user_id" HeaderText="user_id" InsertVisible="False" ReadOnly="True" SortExpression="user_id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Mail" HeaderText="Mail" SortExpression="Mail" />
                    <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                    <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="Instructor_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" DeleteCommand="DELETE FROM [Users] WHERE [user_id] = @user_id" InsertCommand="INSERT INTO [Users] ([Name], [Mail], [DOB], [age]) VALUES (@Name, @Mail, @DOB, @age)" SelectCommand="SELECT [user_id], [Name], [Mail], [DOB], [age] FROM [Users] where role_id='2'" UpdateCommand="UPDATE [Users] SET [Name] = @Name, [Mail] = @Mail, [DOB] = @DOB, [age] = @age WHERE [user_id] = @user_id">
                    <DeleteParameters>
                        <asp:Parameter Name="user_id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Name" Type="String" />
                        <asp:Parameter Name="Mail" Type="String" />
                        <asp:Parameter DbType="Date" Name="DOB" />
                        <asp:Parameter Name="age" Type="Int32" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Name" Type="String" />
                        <asp:Parameter Name="Mail" Type="String" />
                        <asp:Parameter DbType="Date" Name="DOB" />
                        <asp:Parameter Name="age" Type="Int32" />
                        <asp:Parameter Name="user_id" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>


            <asp:GridView CssClass="table table-striped table-bordered table-condensed" ID="Users" runat="server" AutoGenerateColumns="False" DataSourceID="Users_V">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Mail" HeaderText="Mail" SortExpression="Mail" />
                    <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                    <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="Users_V" runat="server" ConnectionString="<%$ ConnectionStrings:GYMConnectionString %>" SelectCommand="SELECT [Name], [Mail], [DOB], [age] FROM [Users] where role_id='2'"></asp:SqlDataSource>

        </div>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Footer" runat="server">
</asp:Content>
